version: '3'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    environment:
      - PYTHONPATH=/app
    restart: unless-stopped
    networks:
      - notes-network

networks:
  notes-network:
    driver: bridge