version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///./notes.db
      - API_KEY=${API_KEY}
    volumes:
      - ./data:/app/data
    restart: unless-stopped
    networks:
      - notes-network

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    depends_on:
      - app
    environment:
      - REACT_APP_API_URL=http://localhost:8000
    networks:
      - notes-network

networks:
  notes-network:
    driver: bridge